[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.9.0"

[dev]
  command = "npm run dev"
  port = 8888
  autoLaunch = false

[functions]
  node_bundler = "esbuild"



